#!/bin/sh

if command -v pamixer &>/dev/null; then
    if [ true == $(pamixer --get-mute) ]; then
        echo 0
        exit
    else
        pamixer --get-volume
    fi
else
    # Ugliest regex I've ever wrote
    wpctl get-volume @DEFAULT_SINK@ | sed 's/.........\.//g'
fi
